name: Feature pipeline

on: [push]

jobs:
  build:
    name: Build
    env:
      SCHEME: "Actions"
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
    runs-on: macOS-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: Build application
      run: |
        set -o pipefail && xcodebuild -project Reciplease/Reciplease.xcodeproj clean -scheme $SCHEME -destination "platform=iOS Simulator,name=$DEVICE" -derivedDataPath $DERIVED_DATA_PATH build-for-testing | xcpretty --color --simple
    - name: Upload products
      uses: actions/upload-artifact@v1
      with:
        name: Products
        path: DerivedData/Build/Products
