name: Build/Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  BuildJob:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild build test -scheme Reciplease -project Reciplease.xcodeproj -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 8'

  DocumentatonJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract Documentation
      uses: SwiftDocOrg/swift-doc@master
      with:
         inputs: "Reciplease"
         module-name: MyLibrary
         output: "Documentation"
    - name: Upload Documentation to Wiki
      uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
         path: "Documentation"
      env:
         GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
